import moment from "moment";

export interface studentDefaultValuesProps {
  anotherContactlivesWithStudent: string;
  firstName: string;
  middleName: string;
  firstLastName: string;
  secondLastName: string;
  idType: string;
  idNumber: number | undefined;
  birthDate: string;
  age: string;
  gender: string;
  birthDepartment: string;
  cityOfBirth: string;
  expeditionPlace: string;
  address: string;
  neighborhood: string;
  studentPhoneNumber: string;
  grade: string;
  lastGrade: string;
  school: string;
  schoolCity: string;
  academicSituation: string;
  reason: string;
  disabilityDescription: string;
  diagnosis: string;
  gradeToApply: string;
  exceptionalPerformance: boolean;
  fatherName: string;
  fatherTel: string;
  fatherProfession: string;
  fatherCompanyName: string;
  fatherJobTitle: string;
  fatherId: string;
  fatherIdExpeditionPlace: string;
  fatherEmail: string;
  fatherlivesWithStudent: string;
  motherName: string;
  motherTel: string;
  motherProfession: string;
  motherCompanyName: string;
  motherJobTitle: string;
  motherId: string;
  motherIdExpeditionPlace: string;
  motherEmail: string;
  motherlivesWithStudent: string;
  eps: string;
  housingStratum: string;
  sisbenLevel: string;
  studentId?: number | undefined;
  studentEmail: string;
  sisbenCarnet: string;
  beneficiaryPrograms: string;
  ethnicity: string;
  indigenousShelter: string;
  conflictVictim: string;
  ejectorDepartment: string;
  ejectorMunicipality: string;
  ejectionDate: string;
  ejectionCertificate: string;
  guardianName: string;
  guardiantTel: string;
  guardiantId: string;
  guardiantExpeditionPlace: string;
  guardiantRelationship: string;
  guardiantEmail: string;
  guardiantlivesWithStudent: string;
  anotherContactName: string;
  anotherContactTel: string;
  anotherContactRelationship: string;
  studentApproval: string;
  faceToFaceAuthorization: boolean;
  admissionDate: string;
}

const date = moment();
const currentDate = date.format("YYYY/MM/DD 12:00:00");

export const studentDefaultValues: studentDefaultValuesProps = {
  firstName: "",
  middleName: "",
  firstLastName: "",
  secondLastName: "",
  idType: "",
  idNumber: undefined,
  birthDate: "",
  age: "",
  gender: "",
  birthDepartment: "",
  gradeToApply: "",
  cityOfBirth: "",
  expeditionPlace: "",
  address: "",
  neighborhood: "",
  studentPhoneNumber: "",
  grade: "",
  lastGrade: "",
  school: "",
  schoolCity: "",
  academicSituation: "",
  reason: "",
  disabilityDescription: "",
  anotherContactlivesWithStudent: "",
  diagnosis: "",
  exceptionalPerformance: false,
  fatherName: "",
  fatherTel: "",
  fatherProfession: "",
  fatherCompanyName: "",
  fatherId: "",
  fatherIdExpeditionPlace: "",
  fatherJobTitle: "",
  fatherEmail: "",
  fatherlivesWithStudent: "",
  motherName: "",
  motherId: "",
  motherIdExpeditionPlace: "",
  motherTel: "",
  motherProfession: "",
  motherCompanyName: "",
  motherJobTitle: "",
  motherEmail: "",
  motherlivesWithStudent: "",
  eps: "",
  studentEmail: "",
  housingStratum: "",
  sisbenLevel: "",
  sisbenCarnet: "",
  beneficiaryPrograms: "",
  ethnicity: "",
  indigenousShelter: "",
  conflictVictim: "",
  ejectorDepartment: "",
  ejectorMunicipality: "",
  ejectionDate: "",
  ejectionCertificate: "",
  guardianName: "",
  guardiantTel: "",
  guardiantId: "",
  guardiantExpeditionPlace: "",
  guardiantRelationship: "",
  guardiantEmail: "",
  guardiantlivesWithStudent: "",
  anotherContactName: "",
  anotherContactTel: "",
  anotherContactRelationship: "",
  studentApproval: "MATRICULADO",
  faceToFaceAuthorization: true,
  admissionDate: currentDate,
};
