export interface studentDefaultValuesProps {
  firstName: string;
  middleName: string;
  lastName: string;
  secondSurname: string;
  colegio: string;
  ciudad: string;
  idType: string;
  idNumber: number | undefined;
  birthDate: string;
  age: string;
  gender: string;
  departmentOfBirth: string;
  cityOfBirth: string;
  expeditionPlace: string;
  dateOfBirth: string;
  address: string;
  barrio: string;
  tel: string;
  grade: string;
  lastGrade: string;
  school: string;
  schoolCity: string;
  academicSituation: string;
  reason: string;
  disability: string;
  disabilityDescription: string;
  diagnosis: string;
  exceptionalAbility: string;
  fatherName: string;
  fatherTel: string;
  fatherProfession: string;
  fatherCompanyName: string;
  fatherJobTitle: string;
  fatherEmail: string;
  fatherlivesWithStudent: string;
  motherName: string;
  motherTel: string;
  motherProfession: string;
  motherCompanyName: string;
  motherJobTitle: string;
  motherEmail: string;
  motherlivesWithStudent: string;
  eps: string;
  socioeconomicLevel: string;
  sisbenLevel: string;
  studentId?: number | undefined;
  sisbenId: string;
  beneficiaryPrograms: string;
  etnia: string;
  resguardo: string;
  conflictVictim: string;
  ExpulsorDepartment: string;
  ExpulsorCity: string;
  expulsionDate: string;
  certificate: string;
  guardianName: string;
  guardiantTel: string;
  guardiantId: string;
  guardiantExpeditionPlace: string;
  guardiantRelationship: string;
  guardiantEmail: string;
  guardiantlivesWithStudent: string;
  anotherContactName: string;
  anotherContactTel: string;
  anotherContactRelationship: string;
  studentState: string;
  AttendInAlternation: string;
}

export const studentDefaultValues: studentDefaultValuesProps = {
  firstName: "",
  middleName: "",
  lastName: "",
  secondSurname: "",
  colegio: "",
  ciudad: "",
  idType: "",
  idNumber: undefined,
  birthDate: "",
  age: "",
  gender: "",
  departmentOfBirth: "",
  cityOfBirth: "",
  expeditionPlace: "",
  dateOfBirth: "",
  address: "",
  barrio: "",
  tel: "",
  grade: "",
  lastGrade: "",
  school: "",
  schoolCity: "",
  academicSituation: "",
  reason: "",
  disability: "",
  disabilityDescription: "",
  diagnosis: "",
  exceptionalAbility: "",
  fatherName: "",
  fatherTel: "",
  fatherProfession: "",
  fatherCompanyName: "",
  fatherJobTitle: "",
  fatherEmail: "",
  fatherlivesWithStudent: "",
  motherName: "",
  motherTel: "",
  motherProfession: "",
  motherCompanyName: "",
  motherJobTitle: "",
  motherEmail: "",
  motherlivesWithStudent: "",
  eps: "",
  socioeconomicLevel: "",
  sisbenLevel: "",
  sisbenId: "",
  beneficiaryPrograms: "",
  etnia: "",
  resguardo: "",
  conflictVictim: "",
  ExpulsorDepartment: "",
  ExpulsorCity: "",
  expulsionDate: "",
  certificate: "",
  guardianName: "",
  guardiantTel: "",
  guardiantId: "",
  guardiantExpeditionPlace: "",
  guardiantRelationship: "",
  guardiantEmail: "",
  guardiantlivesWithStudent: "",
  anotherContactName: "",
  anotherContactTel: "",
  anotherContactRelationship: "",
  studentState: "MATRICULADO",
  AttendInAlternation: "",
};
