export interface interviewDefaultValuesProps {
  accidents: string;
  accidentsDescription: string;
  acquisitionOfLanguage: string;
  additionalComments: string;
  age: string;
  allergies: string;
  allergiesDescription: string;
  babbling: string;
  behaviorAwayFromHome: string;
  behaviorWithAdults: string;
  behaviorWithOtherChildren: string;
  birthDate: string;
  congenitalDiseases: string;
  crawl: string;
  dayDreamDuration: string;
  degreeToApply: string;
  diseaseDiagnosis: string;
  dorsalControl: string;
  educationalInstitutionApplied1: string;
  educationalInstitutionApplied2: string;
  emotionalRelationshipAnotherFamilyMember: string;
  emotionalRelationshipWithFather: string;
  emotionalRelationshipWithMother: string;
  emotionalRelationshipWithPermanentGuardian: string;
  emotionalRelationshipWithThirdParties: string;
  emotionalRelationshipWithotherChildren: string;
  enuresis: string;
  familyHistoryOfDisabilities: string;
  fathersBoth: string;
  fathersBrothers: string;
  firstLastName: string;
  firstName: string;
  firstSentences: string;
  firstWords: string;
  followsInstructions: string;
  guardianName: string;
  guardiantId: string;
  guardiantRelationship: string;
  headControl: string;
  idNumber?: number | undefined;
  illnessesSuffered: string;
  interviewerName: string;
  kindOfDream: string;
  lastSchoolGrade1: string;
  lastSchoolGrade2: string;
  lastSchoolYear1: string;
  lastSchoolYear2: string;
  legalGuardian: string;
  listTeamworkActivities: string;
  mothersBrothers: string;
  nightDreamDuration: string;
  notPeopleStudentLivesWith: string;
  numberOfSiblings: string;
  otherKidsInFamily: string;
  peopleStudentLivesWith: string;
  performance: string;
  pregnancySummary: string;
  psychoMotorDevelopment: string;
  reactionToPunishment: string;
  reasonForUseOfIncubator: string;
  relationshipWithTeachers: string;
  schoolAdaptationProcess: string;
  scholarAchievements: string;
  scholarDifficulties: string;
  secondLastName: string;
  secondName: string;
  siblingsPosition: string;
  studentId: number | undefined;
  studentIdType: string;
  sphincterControl: string;
  studentLivesWithBrothers: string;
  surgery: string;
  surgeryDescription: string;
  teamworkActivities: string;
  treatmentDescription: string;
  treatmentSpecialties: string;
  typeOfBirth: string;
  useOfIncubator: string;
  walk: string;
  withdrawalReason1: string;
  withdrawalReason2: string;
}

export const interviewDefaultValues: interviewDefaultValuesProps = {
  accidents: "",
  accidentsDescription: "",
  acquisitionOfLanguage: "",
  additionalComments: "",
  age: "",
  allergies: "",
  allergiesDescription: "",
  babbling: "",
  behaviorAwayFromHome: "",
  behaviorWithAdults: "",
  behaviorWithOtherChildren: "",
  birthDate: "",
  congenitalDiseases: "",
  crawl: "",
  dayDreamDuration: "",
  degreeToApply: "",
  diseaseDiagnosis: "",
  dorsalControl: "",
  educationalInstitutionApplied1: "",
  educationalInstitutionApplied2: "",
  emotionalRelationshipAnotherFamilyMember: "",
  emotionalRelationshipWithFather: "",
  emotionalRelationshipWithMother: "",
  emotionalRelationshipWithPermanentGuardian: "",
  emotionalRelationshipWithThirdParties: "",
  emotionalRelationshipWithotherChildren: "",
  enuresis: "",
  familyHistoryOfDisabilities: "",
  fathersBoth: "",
  fathersBrothers: "",
  firstLastName: "",
  firstName: "",
  firstSentences: "",
  firstWords: "",
  followsInstructions: "",
  guardianName: "",
  guardiantId: "",
  guardiantRelationship: "",
  headControl: "",
  illnessesSuffered: "",
  interviewerName: "",
  kindOfDream: "",
  lastSchoolGrade1: "",
  lastSchoolGrade2: "",
  lastSchoolYear1: "",
  lastSchoolYear2: "",
  legalGuardian: "",
  listTeamworkActivities: "",
  mothersBrothers: "",
  nightDreamDuration: "",
  notPeopleStudentLivesWith: "",
  numberOfSiblings: "",
  otherKidsInFamily: "",
  peopleStudentLivesWith: "",
  performance: "",
  pregnancySummary: "",
  psychoMotorDevelopment: "",
  reactionToPunishment: "",
  reasonForUseOfIncubator: "",
  relationshipWithTeachers: "",
  schoolAdaptationProcess: "",
  scholarAchievements: "",
  scholarDifficulties: "",
  secondLastName: "",
  secondName: "",
  siblingsPosition: "",
  studentId: undefined,
  studentIdType: "",
  sphincterControl: "",
  studentLivesWithBrothers: "",
  surgery: "",
  surgeryDescription: "",
  teamworkActivities: "",
  treatmentDescription: "",
  treatmentSpecialties: "",
  typeOfBirth: "",
  useOfIncubator: "",
  walk: "",
  withdrawalReason1: "",
  withdrawalReason2: "",
};
